### PR TITLE
type: docs   added new commer link of zulip in README.md under commun…

### LINKED ISSUE #1039: Add the newcomers link of zulip chat for beginners
## Description
For a beginner, along with the channel of #vms we should also add the channel link of #newcomers in README.md, this would make the process a little fast forward for the beginners to communicate with community members and solve their beginner-specific issues.

### Update [Required]
- [ ] [Add the link of #newcomers from anitab-org.zulipchat.com]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by vaibhavarora102**
# Description
Added newcomers zulip link in the ReadMe.

Fixes #1039 

# Type of Change:
**Delete irrelevant options.**

- Documentation

# How Has This Been Tested?
git
Just changed readme

# Checklist:
**Delete irrelevant options.**

- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by satya7289** [comment]
@vaibhavarora102 please follow the commit message [guildline](https://github.com/anitab-org/vms/wiki/Commit-Message-Style-Guide#type).

**Comment by vaibhavarora102** [comment]
I had followed and has taken care
pls accept commit-msg as their  if I change msg again then again I need to squash and that's actually difficult for a beginner like me
thanks

**Review by Ajitesh13 — APPROVED** [review]

**Comment by vaibhavarora102** [comment]
Hi , can I now expect my pr to get merged soon @satya7289

**Review by gaurivn — APPROVED** [review]

**Comment by vaibhavarora102** [comment]
Kindly merge it as soon as possible 
And being beginner I had messed with main branch of this and want to work on other issues too
And for for that I need to re fork it

Hope you understand @satya7289

**Comment by satya7289** [comment]
> Kindly merge it as soon as possible 
> And being beginner I had messed with main branch of this and want to work on other issues too
> And for for that I need to re fork it
> 
> Hope you understand @satya7289 

We will merge it soon. 
You can create new branch from latest develop branch if you want to work on another issue. It will not get mess up. Don't worry.

**Review by isabelcosta — APPROVED** [review]
Great work @vaibhavarora102 🎉 
Thank you for your contribution!

**Pull request merged**
