### PR TITLE
Fixed the volunteer sign up page 

### LINKED ISSUE #950: fix the volunteer sign up page
## Description
When an user tries to sign up as a volunteer , there is an error generated and the form does not load.
## Mocks
Screenshot from 2020-03-17 20-31-41

### Update [Required]
- [ ] code has to be updated

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.5] hours

### PR DESCRIPTION
**Pull request by raghavdhingra**
# Description
Fixed the volunteer sign up page. It has a small bug of an endif template tag. I have added that to it.

Fixes #950

# Type of Change:

- Code
- Quality Assurance

**Code/Quality Assurance Only**

- Bugfix (non-breaking change which fixes an issue)

# How Has This Been Tested?
The signup page is not opening up. I have fixed the issue and tested it by opening up the given Url.

# Checklist:

- [x] My PR follows the style guidelines of this project

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by yashshah2820** [comment]
change the PR title to the work it will do like fixing what any page or feature

**Comment by yashshah2820** [comment]
@anitab-org/qa-team this PR needs a review as I have checked it, the issue is resolved and volunteer sign-up page is working 👍

**Comment by snitin315** [comment]
Is CI broken?

**Comment by yashshah2820** [comment]
@raghavdhingra please do not create PR directly to the develop branch always use branching

**Comment by raghavdhingra** [comment]
yeah sure I'll take care about this next time

**Comment by yashshah2820** [comment]
@raghavdhingra change the PR title to some more meaningful context

**Comment by isabelcosta** [comment]
This is quite easy to review 🙏 Even I can understand this solution :D

**Comment by snitin315** [comment]
I think our first priority should be fixing CI. WDYT @isabelcosta

**Comment by isabelcosta** [comment]
@snitin315 true! and thank you for raising that concern here!
@Harirai mentioned that PR https://github.com/anitab-org/vms/pull/937 and https://github.com/anitab-org/vms/pull/965 are supposed to fix that.

Have you @snitin315 taken a look at those?

**Comment by yashshah2820** [comment]
This PR is ready to be merged @isabelcosta

**Comment by isabelcosta** [comment]
@snitin315 @Harirai I think its ready to merge indeed

What do you think?

**Comment by snitin315** [comment]
Yes, we can merge this PR.

@raghavdhingra thanks for your contribution.

**Comment by isabelcosta** [comment]
@snitin315 thank you so much for helping to confirm this 🙌 
@yashshah2820 thank you for testing this :D I am happy you asked for help about this on Zulip 🤗  
I will merge then :)

**Comment by Monal5031** [comment]
@raghavdhingra Just for future reference, please don't create PRs from develop. Always create a new branch for a new issue

**Comment by isabelcosta** [comment]
+1 to what @Monal5031 said!
Also @raghavdhingra , the commit message did not reflect the change you did, so I updated it to be similar to the PR title.

Regardless of this ^^ congratulations @raghavdhingra on your first PR merged in VMS 👏 👏 👏

**Comment by raghavdhingra** [comment]
@Monal5031 Sure I will take care of it next time
@isabelcosta Thanks and I'll surely use branching the next time I'll make a PR

**Pull request merged**
