### PR TITLE
Added separate templates for feature request and bug report

### LINKED ISSUE #1026: [Documentation] Separate feature and bug template
## Description
Currently we have a single issue template for both `feature` and `bug` issues

### Update 
- [ ] Create separate template for `feature` request and `bug` report.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
.5 hours

### PR DESCRIPTION
**Pull request by Abjcodes**
## Description
added FEATURE_REQUESTS.md and BUG_REPORT.md  as a part of the open-source hack
Fixes #1026 

## Type of Change:
Delete irrelevant options.

- Documentation

## How Has This Been Tested?
Added and previewed markdown files.

## Checklist:
Delete irrelevant options.

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged (no dependencies)

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @Abjcodes let's not change the whole template. please do the following:
1. Let's tweak the current issue template and create two files each for feature request and bug request.
2. you need to create these files under `.github/ISSUE_TEMPLATE/` directory. so create the required folder and place these files under it.
3. Remove current` issue_temple.md` file as we won't require that anymore after adding these two templates.

**Comment by Abjcodes** [comment]
@Kajol-Kumari I have made requested changes. Please review it.

**Review by Kajol-Kumari — COMMENTED** [review]
@Abjcodes Now the templates look better than the previous one but we want it to be similar of [current-template](https://github.com/anitab-org/vms/blob/develop/ISSUE_TEMPLATE.md) so, just use this template for both and modify it according to the bug and feature request. In the current templates that you have made i can't find the `acceptance criteria`, `definition of done` etc. that we have in the current issue template. So pelase follow the current template. Also If something isn't clear, feel free to ask :)

**Comment by Abjcodes** [comment]
@Kajol-Kumari Thanks for the quick response.
I have made relevant changes. Kindly check it and tell me whether any more changes are required.

**Comment by Abjcodes** [comment]
@Kajol-Kumari Can you review this ?

**Review by Kajol-Kumari — APPROVED** [review]
@Abjcodes Thanks for incorporating the changes. LGTM :+1:

**Comment by Kajol-Kumari** [comment]
@Abjcodes please squash all the commits into a single commit so that it can be ready for final review.

**Comment by Abjcodes** [comment]
@Kajol-Kumari Sure. I have squashed the commits. Please check it and tell me whether anything should be changed?

**Comment by Abjcodes** [comment]
@Kajol-Kumari Any updates?

**Review by Kajol-Kumari — APPROVED** [review]

**Comment by Kajol-Kumari** [comment]
@Abjcodes All PRs would be merged after the end of the program, so please work on other issue.

**Review by isabelcosta — APPROVED** [review]

**Comment by isabelcosta** [comment]
Thank you for your contribution @Abjcodes 🎉

**Pull request merged**
