### PR TITLE
 Add installation steps for Django #1032 

### LINKED ISSUE #1032: Add installation steps for Django
## Description
As a new contributor, It would be good if We have a installation guide on Django. Currently we have docker setup instruction. But it would be good if readily instructions are available for downloading, this will make the process fast.

### Update [Required]
- [ ] Add some instructions for django installation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by yash2189**
# Description
Add installation steps for Django

Fixes #1032 

# Type of Change:
- Documentation
Added django installation.

### CODE REVIEW

**Comment by Ajitesh13** [comment]
@yash2189 Thanks for the PR. but it will require the following changes to proceed, as the fix should be a little more simple:
As installing django is already specified in our installation_setup.md, I wish we should just add the link of the "getting started" from the official django documentation and the entire process need not be attached.

**Comment by yash2189** [comment]
So should I just add the link of getting started from django documentation?

**Comment by Ajitesh13** [comment]
Yes, just add the link, with a heading: "Reference for installing django"

**Comment by yash2189** [comment]
Should I create a new PR for the same ?

**Review by SanketDG — CHANGES_REQUESTED** [review]
I am not sure if this is useful at all. Because it should not be that hard for literally _anyone_  to find that link.

@satya7289

**Comment by satya7289** [comment]
> I am not sure if this is useful at all. Because it should not be that hard for literally _anyone_ to find that link.
> 
> @satya7289

I agree with you @SanketDG

**Comment by yash2189** [comment]
Should I make any changes again @satya7289?

**Comment by SanketDG** [comment]
@yash2189 Unfortunately, you will have to close this, since the issue itself is not a valid one

**Pull request closed without merging**
