### PR TITLE
Closes #879 Remove redeclaration of home url

### LINKED ISSUE #879: Define home url only once in urls.py
## Description
The following command throws a warning because the url home is defined twice in the urls.py file in the main directory.

## Mocks
image
image

### Update [Required]
- [ ] Code should be changed so that it is only defined once in urls.py

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by Tlazypanda**
# Description
Code is changed so that home url is declared only once.

Fixes #879 

# Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Locally

# Checklist:
**Delete irrelevant options.**

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Tlazypanda** [comment]
@Monal5031 Have made the changes do take a look :smile:

**Comment by Monal5031** [comment]
@Tlazypanda look at my comment above and make changes accordingly

**Comment by Monal5031** [comment]
ping @Tlazypanda

**Comment by Monal5031** [comment]
Closing due to inactivity

**Pull request closed without merging**
