### PR TITLE
feat: add codecov

### LINKED ISSUE #984: Integrate the codecov to the VMS
## Description
As a Developer,
I need to check the how much code is covered under testing,
so I suggest to integrate codecov for this. 

## Mocks
Able to see the codecov reports on the PR.

### Update [Required]
- [x] requirements.txt
- [x] .travis.yml

## Definition of Done
- [x] All of the required items are completed.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by satya7289**
# Description
Add codecov to the VMS. Now we are able to check the code coverage reports on the PR itself.

Fixes #984 

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?

Screenshot from 2020-07-17 12-05-19

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by husainattar** [comment]
LGTM @satya7289 @yashshah2820

**Comment by yashshah2820** [comment]
@abha224 please provide your review on this PR :)

**Review by isabelcosta — COMMENTED** [review]
What is the requirements.txt document being added as a binary file in this PR?
Is it needed and empty? 
@satya7289

**Comment by satya7289** [comment]
@isabelcosta , there is some update take place in the requirements.txt regarding codecov.
Actually, in this repo, the requirements files always show binary string if some changes take place in the same.

**Review by isabelcosta — APPROVED** [review]

**Pull request merged**
