### PR TITLE
docs: Blog on My OSH Experience

### LINKED ISSUE #1142: blog: OSH Experience
## Description
We need a blog about the OSH experience for the VMS repo including problems faced by a newcomer which may serve as an intro to VMS repo for prospective contributors.

Write a blog on Medium and share the link in a document called outreach-work.md in the “/docs” folder of VMS. So you need to create a post and add a new line to this document.

Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium).

### Update [Required]
- [ ] [Submit Blog. Add line to outreach-work.md]
### Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
## Estimation
[1 Hour] hours

### PR DESCRIPTION
**Pull request by ashwinijha6**
# Description
Blog on my OSH Experience.

Fixes #1142

# Type of Change:

- Outreach

# How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
The Medium link is provided in the outreach-work.md file in docs.

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by keshakaneria** [comment]
@ashwinijha6 I must say you had a great experience which was seen in this amazing blog. 🥳

**Review by keshakaneria — CHANGES_REQUESTED** [review]
Just to make it common for all of them who would write the blog, we can keep the heading named Blogs and below it in bullet `<your full name>: <Title of your blog>` where title of the blog shall be kept hyperlinked to the medium post.

**Comment by keshakaneria** [comment]
Once you've changed, squash them for final ready-to-merge tag :)

**Comment by keshakaneria** [comment]
@ashwinijha6 i suppose you forgot to put a space after `-` which is not allowing it to convert it in a bullet 👀

**Comment by ashwinijha6** [comment]
> @ashwinijha6 i suppose you forgot to put a space after `-` which is not allowing it to convert it in a bullet 👀

yes

**Comment by keshakaneria** [comment]
> > @ashwinijha6 i suppose you forgot to put a space after `-` which is not allowing it to convert it in a bullet 👀
> 
> yes

Also one of your parallel assignee has written his name in All caps format so i guess to make it general you shall too name it in all caps format

**Comment by keshakaneria** [comment]
Squash them so that i can approve for final check :)

**Review by keshakaneria — APPROVED** [review]
Looks good 🥳

**Comment by ashwinijha6** [comment]
> Looks good 🥳

Thanx @keshakaneria 👍

**Review by sanchibansal340 — APPROVED** [review]
Great blog @ashwinijha6!

**Comment by ashwinijha6** [comment]
> Great blog @ashwinijha6!

Thanx @sanchibansal340

**Review by isabelcosta — APPROVED** [review]
Great work @ashwinijha6 ! I also checked the blog post and it is very well structured 👏 
Thank you so much for your contribution!

**Comment by ashwinijha6** [comment]
> Great work @ashwinijha6 ! I also checked the blog post and it is very well structured 👏
> Thank you so much for your contribution!

Thankyou @isabelcosta it really means a lot to me. OSH was a great experience, looking forward to make more contributions 😄

**Comment by isabelcosta** [comment]
@ashwinijha6 That is awesome to know! 🤗

**Pull request merged**
