### PR TITLE
[WIP] Travis CI fix

### LINKED ISSUE #934: Fix error on travis CI so the test suite can be executed
## Description
As a contributor,
I need to have my changes tested on travis CI,
so that I can assure that my changes dont break anything in current version of code.

## Mocks
image

### Update [Required]
- [ ] .travis.yml file to fix the build so the test suite can run properly

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by Kishan-Dhakan**
Getting Travis CI logs for the apps

# Description
There are 8 commits. The description is as follows:

Commit 1 of 8: To get Travis CI logs for the app registeration only
Commit 2 of 8: To get Travis CI logs for the app shift only
Commit 3 of 8: To get Travis CI logs for the app job only
Commit 4 of 8: To get Travis CI logs for the app event only
Commit 5 of 8: To get Travis CI logs for the app organization only
Commit 6 of 8: To get Travis CI logs for the app administrator only
Commit 7 of 8: To get Travis CI logs for the app volunteer only
Commit 8 of 8: To get Travis CI logs for the app authorization only

Fixes # [ISSUE]
fixes #934 

# Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
This has been tested by running a trigger build on Travis CI.

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Kishan-Dhakan** [comment]
@sammy1997 @Monal5031 Kindly suggest changes if any :)

**Comment by Monal5031** [comment]
@Kishan-Dhakan I asked to create commits on GH so travis could run 😂 Not locally create different commits and push all at the same time.

Now do this:
1. Squash all your commits, coz we don't want the clutter
2. After squash, create the commits again and push them to GH 1 by 1 and check the travis CI started for that commit or not.

**Comment by Kishan-Dhakan** [comment]
Okay I got that! I was checking Travis CI on my account after every commit, hence the confusion. Working on the changes :)

**Comment by Kishan-Dhakan** [comment]
@Monal5031 @sammy1997 kindly review this :)

**Comment by Monal5031** [comment]
This needs to be merged after #965 right?

**Comment by mayburgos** [comment]
@Kishan-Dhakan Closing this PR. I think @satya7289's PR does the same, if not similar fixes. Also, checked with Kishan on [Zulip](https://anitab-org.zulipchat.com/#narrow/stream/222539-vms/topic/Testing.20Pipeline/near/202623702) to see if there was any issues about closing his PR.

**Pull request closed without merging**
