### PR TITLE
code: python decouple added 

### LINKED ISSUE #873: Configure django-decouple instead of environment variables
## Description
As a Member,
I need  to configure django-decouple
so that I can eliminate the hassle of environment variables.

## Mocks
Generally django uses environment variables to set various secrets in settings.py of the project like Database creds, Secret Keys, Emailing ID details, allowed hosts, debug status.
Using environment variables is usually a hassle and is prone to error.
Django decouple takes the settings parameters from a .env file, hence even developers don't need to export environment variables to work and can simply use an example .env file.
Similarly even on the production server, this will simplify things, making it faster to deploy.
 [Read More](https://pypi.org/project/python-decouple/)
[Read More](https://medium.com/@nithinkvijayan/https-medium-com-nithinkvijayan-separating-django-application-config-and-secrets-from-code-python-decouple-e0787d2bcc2a)

### Update [Required]
- Add django-decouple to requirements.txt
- Make all fields in settings.py dynamic with django-decouple
- modify travis.yml accordingly

### Enhancement to Update [Optional]
- [ ]  Write tests

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by yashshah2820**
# Description
I have used python-decouple to access the environment variables, I have also added the example env file for the developers, I have added a line to the travis CI file so that the test can run without any breaking. I have added .env file to the gitignore and python-decouple package to requirements.txt

Fixes #873 

# Type of Change:
**Delete irrelevant options.**

- Code

# How Has This Been Tested?
By locally running the site on the server, if the server successfully gets created  and there are breaks in the functioning of the site then the code is written correctly 

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yashshah2820** [comment]
It will be a separate issue to update the doc I think :)

**Comment by satya7289** [comment]
> It will be a separate issue to update the doc I think :)

Ok, fine. When it merges, I'll log the issue for a documentation update.

**Comment by yashshah2820** [comment]
requirements.txt file is not shown in the GitHub repo I don't know why but the file is there it is not deleted 👍

**Comment by SanketDG** [comment]
https://github.com/yashshah2820/vms/blob/decouple/requirements.txt

Seems to be removed here

**Comment by yashshah2820** [comment]
@SanketDG I have added the requirements.txt contents once again, PTAL :)

**Comment by SanketDG** [comment]
@yashshah2820 Can you trigger an empty push?

**Comment by yashshah2820** [comment]
@SanketDG are you talking with respect to the Travis CI, the CI is broken

**Comment by rpattath** [comment]
@satya7289 please provide a review approval. So that @anitab-org/qa-team can start testing.

**Comment by yashshah2820** [comment]
@rpattath @satya7289 said looks good to me in the review, so I guess it is good to go :)

**Comment by yashshah2820** [comment]
@satya7289 but it will take time I guess 🤔

**Comment by satya7289** [comment]
> @satya7289 but it will take time I guess

No, it is done from my side need review and test.

**Comment by rpattath** [comment]
@yashshah2820 I am hitting the following error when trying to test this PR:
```
$ python manage.py runserver 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rpattath/vms/venv/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rpattath/vms/vms/vms/settings.py", line 11, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
(venv) [rpattath@rpattath vms]$ pip install decouple
Collecting decouple
  Downloading decouple-0.0.7.tar.gz (3.3 kB)
Building wheels for collected packages: decouple
  Building wheel for decouple (setup.py) ... done
  Created wheel for decouple: filename=decouple-0.0.7-py3-none-any.whl size=4483 sha256=abb242b58c9f775ea445a07671569eee06138cc2d029c236573232c6db32c20b
  Stored in directory: /home/rpattath/.cache/pip/wheels/df/e5/10/ed0fddfe578a85f2b2cc180ffe178cd4720f46e56e1b2bc99a
Successfully built decouple
Installing collected packages: decouple
Successfully installed decouple-0.0.7
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/home/rpattath/vms/venv/bin/python3 -m pip install --upgrade pip' command.
(venv) [rpattath@rpattath vms]$ python manage.py runserver 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rpattath/vms/venv/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rpattath/vms/vms/vms/settings.py", line 11, in <module>
    from decouple import config
ImportError: cannot import name 'config' from 'decouple' (/home/rpattath/vms/venv/lib/python3.8/site-packages/decouple/__init__.py)
```
I am try to do the following as provided in the PR description:
"By locally running the site on the server, if the server successfully gets created and there are breaks in the functioning of the site then the code is written correctly"

Please provide detailed steps to test this PR.

**Comment by satya7289** [comment]
> @yashshah2820 I am hitting the following error when trying to test this PR:
> 
> ```
> $ python manage.py runserver 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 308, in execute
>     settings.INSTALLED_APPS
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 56, in __getattr__
>     self._setup(name)
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 41, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 110, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/home/rpattath/vms/venv/lib64/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/rpattath/vms/vms/vms/settings.py", line 11, in <module>
>     from decouple import config
> ModuleNotFoundError: No module named 'decouple'
> (venv) [rpattath@rpattath vms]$ pip install decouple
> Collecting decouple
>   Downloading decouple-0.0.7.tar.gz (3.3 kB)
> Building wheels for collected packages: decouple
>   Building wheel for decouple (setup.py) ... done
>   Created wheel for decouple: filename=decouple-0.0.7-py3-none-any.whl size=4483 sha256=abb242b58c9f775ea445a07671569eee06138cc2d029c236573232c6db32c20b
>   Stored in directory: /home/rpattath/.cache/pip/wheels/df/e5/10/ed0fddfe578a85f2b2cc180ffe178cd4720f46e56e1b2bc99a
> Successfully built decouple
> Installing collected packages: decouple
> Successfully installed decouple-0.0.7
> WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
> You should consider upgrading via the '/home/rpattath/vms/venv/bin/python3 -m pip install --upgrade pip' command.
> (venv) [rpattath@rpattath vms]$ python manage.py runserver 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 308, in execute
>     settings.INSTALLED_APPS
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 56, in __getattr__
>     self._setup(name)
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 41, in _setup
>     self._wrapped = Settings(settings_module)
>   File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 110, in __init__
>     mod = importlib.import_module(self.SETTINGS_MODULE)
>   File "/home/rpattath/vms/venv/lib64/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/rpattath/vms/vms/vms/settings.py", line 11, in <module>
>     from decouple import config
> ImportError: cannot import name 'config' from 'decouple' (/home/rpattath/vms/venv/lib/python3.8/site-packages/decouple/__init__.py)
> ```
> 
> I am try to do the following as provided in the PR description:
> "By locally running the site on the server, if the server successfully gets created and there are breaks in the functioning of the site then the code is written correctly"
> 
> Please provide detailed steps to test this PR.

Try with python 3.7.

**Comment by yashshah2820** [comment]
@rpattath run pip install -r requirements.txt

**Comment by rpattath** [comment]
@yashshah2820 still hitting the issue https://gist.github.com/rpattath/606c3dc53fe383f2d5cd00e1093d5d87

@satya7289 python 3.8 support was just added then why do we have to test with python 3.7?

**Comment by yashshah2820** [comment]
@rpattath add a file called .env in the project where manage.py is located then copy the contents .env.example to the .env file then run the server

**Comment by rpattath** [comment]
@yashshah2820 I am still hitting the same issue. I think we have to wait for this [PR](https://github.com/anitab-org/vms/pull/976) to be merged, so that these issues can be caught when travis CI runs and then qa-team could do the integration testing. I am moving this PR to `Needs review`

```
$ python manage.py runserver 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/rpattath/vms/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/rpattath/vms/venv/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rpattath/vms/vms/vms/settings.py", line 11, in <module>
    from decouple import config
ImportError: cannot import name 'config' from 'decouple' (/home/rpattath/vms/venv/lib/python3.8/site-packages/decouple/__init__.py)
(venv) [rpattath@rpattath vms]$ cat .env
SECRET_KEY = foobarbaz

DEBUG = True

ALLOWED_HOSTS = *

# Database settings

DB_NAME = vms
DB_USER = vmsadmin
DB_PASSWORD = 0xdeadbeef
DB_HOST = localhost

# Email settings

EMAIL_HOST = localhost
EMAIL_PORT = 1025
```

**Comment by yashshah2820** [comment]
did you run `pip install python-decouple`

**Comment by rpattath** [comment]
@yashshah2820 why isn't that package included in requirements.txt? I strongly feel that this PR should be tested and merged only after Travis is fixed for this project. @SanketDG @satya7289 @Monal5031 @isabelcosta please give your opinions.

**Comment by yashshah2820** [comment]
@rpattath the package is included in the requirements.txt file, PTAL

**Comment by masterchief01** [comment]
@yashshah2820 running `$ pip install -r requirements.txt` and creating the required `.env` file solves the issues encountered earlier and I am able to setup the server.

> By locally running the site on the server, if the server successfully gets created and there are breaks in the functioning of the site then the code is written correctly

Could you please elaborate on the meaning of..

> there are breaks in the functioning of the site 

Could you please attach a screenshot of the desired behaviour so that I may cross-check.
My output looks like this..

My terminal
Screenshot from 2020-06-25 00-22-49

Login
Screenshot from 2020-06-25 00-20-19

Successful Login
Screenshot from 2020-06-25 00-20-31

**Comment by yashshah2820** [comment]
@masterchief01 did you test this PR locally looking at the screenshots the test seems successful :)

**Comment by mayburgos** [comment]
@yashshah2820 Sorry, I merged the other PRs that caused a conflict. Can you resolve that and we'll merge?

**Comment by yashshah2820** [comment]
@mayburgos the conflict is resolved 😄

**Comment by mayburgos** [comment]
@yashshah2820 I still need help with the [commit type](https://github.com/anitab-org/vms/wiki/Commit-Message-Style-Guide) this PR falls under.

**Pull request merged**
