### PR TITLE
Docs: OSH Experience

### LINKED ISSUE #1142: blog: OSH Experience
## Description
We need a blog about the OSH experience for the VMS repo including problems faced by a newcomer which may serve as an intro to VMS repo for prospective contributors.

Write a blog on Medium and share the link in a document called outreach-work.md in the “/docs” folder of VMS. So you need to create a post and add a new line to this document.

Mention AnitaB.org as a publication while publishing the blog/article (called: story on medium).

### Update [Required]
- [ ] [Submit Blog. Add line to outreach-work.md]
### Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
## Estimation
[1 Hour] hours

### PR DESCRIPTION
**Pull request by decon-harsh**
Blog for OSH

Fixes #1142 

# Type of Change:
- Outreach

# Checklist:
- [X] My PR follows the style guidelines of this project

### CODE REVIEW

**Comment by keshakaneria** [comment]
@decon-harsh  That's amazing! Good that you learnt a lot.

**Review by keshakaneria — CHANGES_REQUESTED** [review]
Just to make it common for all of them who would write the blog, we can keep the heading named `Blogs` and below it in bullet `<your full name>: <Title of your blog>` where title of the blog shall be kept hyperlinked to the medium post.

**Comment by decon-harsh** [comment]
Sure I will do it not a problem

**Comment by keshakaneria** [comment]
> Sure I will do it not a problem

Squash them once it is done so that PR is ready to merge :)

**Comment by decon-harsh** [comment]
Owh i forgot bullet point😥

**Review by keshakaneria — DISMISSED** [review]
Looks good now

**Review by sanchibansal340 — APPROVED** [review]
Looks good to me.

**Review by isabelcosta — APPROVED** [review]
Great work @decon-harsh 🎉 
Thank you for contributing and sharing your experience through a blog post!

**Comment by isabelcosta** [comment]
@keshakaneria @sanchibansal340 can you please review this PR again, there were some merge conflicts I just solved.

**Review by keshakaneria — APPROVED** [review]

**Pull request merged**
