### PR TITLE
Email sent to user for password verification #1030

### LINKED ISSUE #1030: Add task using Celery to send email verification for reset password
## Description
In order to login into the system using forgot password, I need to verify my email address to get logged in to change the old password with the new one. Currently, the email is displayed in the console itself.

### Update [Required]
- [ ] Add tasks using Celery
- [ ] Email should be sent to the email address instead of printing it in console.

Celery is an asynchronous task scheduler which helps to run different process in background which can be used here in order to create tasks for mailing system.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
# Description
Now the email is sending to the user for password reset

Fixes #1030 

# Type of Change:
Change in settings.py

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
@keshkaneria Take a look at the changes now..

**Review by SanketDG — CHANGES_REQUESTED** [review]
I must be missing something, but was anything mentioned in the issue implemented at all? :thinking:

**Comment by kritikaparmar-programmer** [comment]
@keshakaneria asked me to do what I know to send email to the user for forgot password..
And I told her that I 'll not use Celery
@SanketDG

**Comment by SanketDG** [comment]
But putting actual/real settings in the settings file does not solve the actual problem, right?

I must be missing something here, apologies.

**Comment by keshakaneria** [comment]
> But putting actual/real settings in the settings file does not solve the actual problem, right?
> 
> I must be missing something here, apologies.

Yes, I thought the things which she has done earlier might be compatible to resolve this problem. But i guess we will have to look into it @kritikaparmar-programmer. Can you do it with celery as defined in the issue?

**Comment by kritikaparmar-programmer** [comment]
@keshakaneria Please assign this issue to someone else.. I tried but not able to do..

**Comment by keshakaneria** [comment]
> @keshakaneria Please assign this issue to someone else.. I tried but not able to do..

Alright :)

**Pull request closed without merging**
