### PR TITLE
fix: solved travis ci error, so that test suites can be executed successfully

### LINKED ISSUE #934: Fix error on travis CI so the test suite can be executed
## Description
As a contributor,
I need to have my changes tested on travis CI,
so that I can assure that my changes dont break anything in current version of code.

## Mocks
image

### Update [Required]
- [ ] .travis.yml file to fix the build so the test suite can run properly

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by satya7289**
# Description
Currently, the Travis CI execution is causing an error. Screenshot below was provided by Satya.
TravisCI.org Error Screenshot

This PR fixes the error by updating the variables in the travis.yml file and also commented out the [12 tests that failed](https://github.com/anitab-org/vms/issues/979).

Out of 329, 320 test cases passed on my PR.

**Additional Information**
- I have commented out the test suites that were failing. I also documented them and [created an issue](https://github.com/anitab-org/vms/issues/979) for others to claim to fix.
The following test suites are failing and have been commented out by me: 
   - 1+4 failing testcase issue in administrator.tests.test_settings
   - 2+2 failing testcases registration.tests.test_functional_admin and registration.tests.test_functional_volunteer
   - 1 failing testcase for volunteer.tests.test_volunteerProfile
   - 1+1 failing testcases for shift.tests.test_log_hours and shift.tests.test_cancel_shift_registration

Fixes #934

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
I tested this PR by running locally one by one. It consumes literally a lot of my time for finding where the issue is present.

Also, I tested these by enabling the travis ci for the forked repo on my travis ci account.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yashshah2820** [comment]
@Harirai certainly if that's the case then no problem

**Comment by yashshah2820** [comment]
@satya7289 link the corresponding issue :)

**Comment by satya7289** [comment]
> @satya7289 link the corresponding issue :)

I have added in description of the pr in the additional info section. After this will merge(then Travis CI is stable) I will create an issue for remaining test cases.

**Comment by satya7289** [comment]
> LGTM from a first look
> 
> About the failing tests, any reason on why you can'r fix them yourselves?

I'll fix failing test case in the new issue because some of them might need to change the backend code also.
Actually aim of this pr is to stablish the Travis CI(because of this many things stopped in this repo), after this merge a new issue will be created which cover remaining testcases(we are not removing these, we will cover in next issue).

If any changes need to done other than commented testcases, please let me know. Thanks ☺️

**Comment by rpattath** [comment]
@SanketDG could you provide an approval if @satya7289 's comment is reasonable. Once this PR has 2 approvals @anitab-org/qa-team can start testing.

**Comment by rpattath** [comment]
@satya7289 @yashshah2820 how can this PR be tested by QA Team? I see the Travis CI has passed for this PR, would that be good enough testing for this PR to be merged?

**Comment by isabelcosta** [comment]
@satya7289 can you please link this to an issue and add more description in the pull request description, so that other reviewers and testers can know what you are doing here :)

**Pull request merged**
