### PR TITLE
Codcov Integeration

### PR DESCRIPTION
**Pull request by satya7289**
# Description
Add codecov

Fixes # [ISSUE]

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by mayburgos** [comment]
@satya7289 When you open a PR, please try to be as detailed as possible. I've updated your [last PR](https://github.com/anitab-org/vms/pull/976). Use that as a reference for future PRs.

**Comment by mayburgos** [comment]
Also, you're showing older commits. When you create a new branch, do you create it from develop branch? Those old commits shouldn't appear here.

**Comment by mayburgos** [comment]
> @satya7289 When you open a PR, please try to be as detailed as possible. I've updated your [last PR](https://github.com/anitab-org/vms/pull/976). Use that as a reference for future PRs.

Please update the PR by filling out the template and following the [commit style](https://github.com/anitab-org/vms/wiki/Commit-Message-Style-Guide).

**Comment by satya7289** [comment]
closing this with the reference of this [PR](https://github.com/anitab-org/vms/pull/983)

**Pull request closed without merging**
