### PR TITLE
docs: add codecov badge & update title

### LINKED ISSUE #1062: Add badges to the Readme File for codecov
## Description
Add badges to the Readme File for codecov after this [PR.](https://github.com/anitab-org/vms/pull/983) & update the titile of the Readme file to `Volunteer Management System(VMS)`

## Definition of Done
- [x] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by aniketrb-github**
# Description
- Add a codecov badge (#1062) 
- Updated the project title in readme file from `AnitaB.org Portal - VMS project` to `Volunteer Management System(VMS)`

Fixes #1062

# Type of Change:
- Documentation

# How has this been tested?
`Before changes were made:`
before-1062-changes

`After changes were made:`
after-1062-change

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by aniketrb-github** [comment]
Hi, @satya7289 and @isabelcosta ,
Here's the new pull request. Kindly review it Thanks.

**Review by satya7289 — APPROVED** [review]
LGTM

**Review by isabelcosta — APPROVED** [review]
Great work @aniketrb-github 👏 
Thank you for contributing with this issue again 🙌

**Comment by aniketrb-github** [comment]
> Great work @aniketrb-github 👏 
> Thank you for contributing with this issue again 🙌 

Thank you for guiding me. 🙂

**Pull request merged**
