### PR TITLE
modified create shifts datepicker for better user experience

### PR DESCRIPTION
**Pull request by abha224**
# Description
Modified the datepicker to show relavant dates and help admin create a shift without confusion.  
Fixes [#939 ](https://github.com/anitab-org/vms/issues/939)

# Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
The code has been tested on local machine. 

# Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by abha224** [comment]
@Monal5031 Kindly review this and let me know if any changes should be made. :smiley:

**Comment by abha224** [comment]
oh ok. Will make the changes, sorry.

**Comment by abha224** [comment]
@yashshah2820 Yes, I had made a mistake at that time and Monal had rightly pointed it out. I will update the gif in a few days if that's ok, currently I'm a bit occupied. sorry in advance for the delay.

**Comment by yashshah2820** [comment]
@abha224 go-ahead 😄

**Comment by yashshah2820** [comment]
@abha224 can you change the PR title according to the [commit guidelines](https://github.com/anitab-org/vms/wiki/Commit-Message-Style-Guide)

**Comment by mayburgos** [comment]
Abha asked to close it since it's been a long time and she's changed workstations so no longer has the screenshot to add to this PR.

**Pull request closed without merging**
