### PR TITLE
fix: Admin registration issue

### LINKED ISSUE #1002: Bug: Registration from the admin side is not working
## Description
As an admin I need to be able to register with the vms website, so that I can check on the volunteer's status. Currently, when an admin tries to register with vms, there is an error displayed.

## Mocks
Screenshot from 2020-07-30 22-38-34

## Acceptance Criteria
The admin is successfully able to register with vms

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

### PR DESCRIPTION
**Pull request by satya7289**
# Description
Fix admin registration issue while signing up.

Fixes #1002

# Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
successfully able to register.
Screenshot from 2020-07-31 12-42-11

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by yashshah2820** [comment]
@anitab-org/qa-team this PR is ready to be tested

**Review by devkapilbansal — APPROVED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review - Done

2. All possible responses (positive and negative tests) were tested as below:

   * _Test Description_  
     _Screenshot/gif_: (From develop branch)
error_admin 
     _Result_:  From this PR
tested

5. Status of PR can Changed to: Ready to Merge.

**Comment by isabelcosta** [comment]
@devkapilbansal thank you so much for testing this!

**Review by isabelcosta — APPROVED** [review]
wow, a simple change and such an impact!
Thank you for your contribution @satya7289

**Pull request merged**
