### PR TITLE
docs: add a python version badge (#1052)

### LINKED ISSUE #1052: Add a badge for Python version in README.md
## Description
README.md should have a badge for denoting the version of python needed.

## Mocks
README of [mentorship-backend](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md).

Screenshot from 2020-08-29 20-56-52

## Definition of Done
- [ ] Badge should be added with appropriate version.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by aniketrb-github**
# Description
Added a python version badge

Fixes #1052

# Mock
anitab-org-vms-fix1052

# Type of Change:
- Documentation

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
Hello @aniketrb-github . Thanks for showing interest in this project. I just wanted to know if you are an OSH participant.

**Comment by aniketrb-github** [comment]
> Hello @aniketrb-github . Thanks for showing interest in this project. I just wanted to know if you are an OSH participant.

@rkpattnaik780 No, as of now I'm not a participant of the OSH event. If the registration is mandatory and if it restricts me from contributing, can you please guide me or direct me towards the same. Thanks.

**Review by gaurivn — COMMENTED** [review]
The [second commit](https://github.com/anitab-org/vms/pull/1054/commits/20d8d306fa78bb91c5990c198390b333602723d6) fixes Issue #1047, not this one, pls undo the change.

**Comment by aniketrb-github** [comment]
> The [second commit](https://github.com/anitab-org/vms/pull/1054/commits/20d8d306fa78bb91c5990c198390b333602723d6) fixes Issue #1047, not this one, pls undo the change.

Yes, I have mistakenly clubbed it in this PR. 
Should I create a separate PR with only code changes related #1057...?

**Comment by gaurivn** [comment]
@aniketrb-github, kindly read the [contributing guidelines](https://github.com/anitab-org/vms/blob/develop/CONTRIBUTING.md), would be better to work on an issue after it is assigned to you.

**Comment by gaurivn** [comment]
> > The [second commit](https://github.com/anitab-org/vms/pull/1054/commits/20d8d306fa78bb91c5990c198390b333602723d6) fixes Issue #1047, not this one, pls undo the change.
> 
> Yes, I have mistakenly clubbed it in this PR.
> Should I create a separate PR with only code changes related #1057...?

No, you only have to undo the second commit, undo the changes you made in the second commit,

**Comment by aniketrb-github** [comment]
> > > The [second commit](https://github.com/anitab-org/vms/pull/1054/commits/20d8d306fa78bb91c5990c198390b333602723d6) fixes Issue #1047, not this one, pls undo the change.
> > 
> > 
> > Yes, I have mistakenly clubbed it in this PR.
> > Should I create a separate PR with only code changes related #1057...?
> 
> No, you only have to undo the second commit, undo the changes you made in the second commit.

Ok got it. Yes, I won't raise a new PR with the corrected changes and will rather wait until it's assigned to me. Thanks.

**Comment by rkpattnaik780** [comment]
Hello @aniketrb-github . I am closing this PR since it does not comply with the guidelines. Feel free to comment on the issue again after 00:00 IST. Issues will be assigned on first come first serve basis. You can raise a PR only after an issue has been assigned.

**Comment by aniketrb-github** [comment]
> Hello @aniketrb-github . I am closing this PR since it does not comply with the guidelines. Feel free to comment on the issue again after 00:00 IST. Issues will be assigned on first come first serve basis. You can raise a PR only after an issue has been assigned.

Sure @rkpattnaik780. Thanks.

**Pull request closed without merging**
