### PR TITLE
Added Header footer

### LINKED ISSUE #1034: [UI] Wireframe Design for homepage
## Description
Currently we have a simple home page with a logo, few options and a basic introduction.
## Mocks
imageedit_2_7230070166

### Update
- [ ] Create a proper Home page UI using wireframe containing proper header, footer and other functionalities in a well organised and more attractive way.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by pallavithakare28**
I am done with the setup and trying to make changes. Added header, footer and looking forward to making more attractive changes.

# Description
Trying to add header and footer and working on the other aspects.

Fixes #1034 

# Type of Change: Wireframe design for Home page

- Code
- User Interface
Final_wireframe

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by pallavithakare28** [comment]
@Kajol-Kumari Hello mam, I have added the screenshots. Please let me know where I have to correct it.  And guide me for further.

**Comment by Kajol-Kumari** [comment]
Hey @pallavithakare28 please do any coding stuff in this PR, you just need to make the wireframe design for this issue. And regarding the design, Current header looks much better than the one you have shared here. so if you can make the header design having UI better than the current version, it would be grate otherwise keep the current header only.

**Comment by pallavithakare28** [comment]
@Kajol-Kumari I will try my level best to make it attractive. I will definitely do it soon. :)

**Comment by pallavithakare28** [comment]
@Kajol-Kumari Hello mam, I have attached a wireframe design in the description. Is it correct? The issue is expecting for the solution, please suggest me how to proceed further.

**Comment by Kajol-Kumari** [comment]
Hey @pallavithakare28 I am sorry if i was not clear to you but you just need to use tools like `figma` or `balsamiq` to make the UI/UX design for the home page, take it's screenshot and add it under wireframes folder(create this folder as we don't have it currently) and make the PR. We don't need any code or anything else for this issue. Just the design image is required. If you still need any clarifications, feel free to ask it.

**Comment by pallavithakare28** [comment]
Hi @Kajol-Kumari, Please refer to my [new PR](https://github.com/anitab-org/vms/pull/1090) since I have closed this one. Thanks

**Pull request closed without merging**
