### PR TITLE
docs: update file Code Of Conduct & all its respective references (#1047)

### LINKED ISSUE #1047: Create a code_of_conduct.md file
## Description
As a contributor, I need to modify the Code of Conduct, so that I understand about the organisation better and don't do something that breaches that code of conduct accidently.
1. The content should be consistent with [Code of Conduct here](https://github.com/anitab-org/documentation/blob/master/Contributing/CODE_OF_CONDUCT.md)
2. And then update the code of conduct link in **Readme.md**>>Contributing section as well as in **Contributing.md**.
3. Add the updated Code of Conduct file to doc folder.

## Acceptance Criteria
- [ ] Update [Required]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

## Note
This issue will be assigned from September 1, 2020

### PR DESCRIPTION
**Pull request by aniketrb-github**
# Description
- Renamed filename from `code_of_conduct.md` to `CODE_OF_CONDUCT.md`
- Updated the file content so that any individual can refer and adhere to the guidelines laid by the community and can avoid violating any of them.
- Updated the reference link in `Readme.md` >> `Contribute` 
- Updated the reference link in `Contributing.md`
- Added updated Code of Conduct file to `doc` folder.

Fixes #1047

# Type of Change:
- Documentation

# How has this been tested?
`Before the Code changes were made:`
before-1047-fix

`After the Code changes were made:`
after-1047-fix

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented on my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by aniketrb-github** [comment]
Hello @sanchibansal340, Can you please review this PR for #1047 
Thanks

**Comment by sanchibansal340** [comment]
@aniketrb-github Instead of adding the code_of_conduct file to docs please add it outside and delete the previous Code of Conduct and you will be done :)

**Comment by aniketrb-github** [comment]
> @aniketrb-github Instead of adding the code_of_conduct file to docs please add it outside and delete the previous Code of Conduct and you will be done :)

Oh Ok. I added it since the description said so. No problem.
So, I just have to "delete the newly added file from DOCS folder" right? which means I just have to revert that specific commit.
And since you said: "add it outside", so the codeOfCoduct file already exists at the root level, which I have corrected as a part of the fix for this issue.

**Comment by aniketrb-github** [comment]
Due to the issue description, I preferred to keep my commits independent/modular which helped me. I just learned that if all the small commits were clubbed into a single commit, I would have not been able to revert the commit & incorporate the new requirement. So I just have reverted the code commit which was "Adding file: codeOfConduct to DOCS folder".
I hope this suffices it @sanchibansal340. Can you please review it once. Thanks. :)

**Comment by sanchibansal340** [comment]
@aniketrb-github There are some inconsistencies with the content. Would it be possible to delete the previous code of conduct file and commit the one you added in the docs folder. Thanks. :)

**Comment by sanchibansal340** [comment]
Also please make sure you have changed the links in the README and Contributing guidelines which are in the root directory and not the ones in the docs folder.

**Comment by aniketrb-github** [comment]
> @aniketrb-github There are some inconsistencies with the content. Would it be possible to delete the previous code of conduct file and commit the one you added in the docs folder. Thanks. :)

Hi @sanchibansal340, regarding your comment for "inconsistency with content", I have used this [CodeOfConduct file](https://github.com/anitab-org/documentation/blob/master/Contributing/CODE_OF_CONDUCT.md) as a reference which was mentioned in the issue description.

And, regarding the 2nd comment, Yes I have updated the links of the files which are present at the root location and not the ones in DOCS folder.

**Review by aniketrb-github — COMMENTED** [review]
After seeing your comment regarding the inconsistency of content I did a recheck on this commit which I think are having no discrepancies with this [provided link](https://github.com/anitab-org/documentation/blob/master/Contributing/CODE_OF_CONDUCT.md) from the [issue description.](https://github.com/anitab-org/vms/issues/1047) 
Can you please check & confirm once @sanchibansal340. Thanks. :)

**Comment by aniketrb-github** [comment]
Hi @sanchibansal340. Can you check my comments and Please l review my PR once. Thanks

**Comment by sanchibansal340** [comment]
Will do @aniketrb-github

**Comment by sanchibansal340** [comment]
Looks good to me 👍🏼

**Review by sanchibansal340 — APPROVED** [review]

**Comment by aniketrb-github** [comment]
Thanks @sanchibansal340.
How should I proceed further now, or for this PR what is the next phase?

**Review by SanketDG — APPROVED** [review]
Good to merge :tada:

**Comment by aniketrb-github** [comment]
hi @sanchibansal340 , when does this PR get merged?

**Comment by sanchibansal340** [comment]
@aniketrb-github it will be merged after OSH ends i.e. after September

**Comment by aniketrb-github** [comment]
> @aniketrb-github it will be merged after OSH ends i.e. after September

Okay.
@sanchibansal340 so will it be okay if I delete my forked branch? or will the deletion affect the PR merge?
Since the PR is created from my forked repo which had a child branch `vms-1047`
I had forked the develop branch and have solved 2 issues, but now the fork is a stale repo and is trailing with a no. of commits.

**Review by isabelcosta — APPROVED** [review]
Great work @aniketrb-github 🎉 Thank you for your contribution!

**Pull request merged**
