### PR TITLE
Improved the form filling process for the admin (issue #938)

### LINKED ISSUE #938: Improving the form filling process for the admin
## Description
When the admin searches for a volunteer , instead of filling out all the form fields
(some of which are optional) ,  can we add * for the relevant fields to be filled . This will make it easier for the admin to navigate and search.

## Mocks
NA

### Update [Required]
- [ ] identify mandatory form field names
- [ ] update form field names 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.5] hours

### PR DESCRIPTION
**Pull request by kjain0073**
# Description
Added the REQUIRED feature which helps the admin to navigate and search the volunteers faster by filling out the minimum number of relevant fields that show the required feature as soon as the "search" button is pressed.

Fixes #938 

# Type of Change
* Code

**Code/Quality Assurance Only**
* Enhancement

# How has this been tested?
This code has been tested on a local machine

# Checklist
- [x] My PR follows the style guideline for this project.
- [x] I have performed a self-review of my own code or material.

**Code/Quality Assurance Only**
- [x] My code generates no new warnings.

### CODE REVIEW

**Comment by Harirai** [comment]
@kjain0073 We mistook the issue as "Required" fields, actually they are not compulsorily required while searching. They are just to show admin that these fields were required at the time of signing up.

So you just need to change search.html (add * after relevant fields) in templates of the volunteer.

@Monal5031 Sorry sir I misunderstood the issue first, I hope I'm not making any mistake now. :worried:

**Comment by kjain0073** [comment]
@Harirai  if I didn't misunderstand this, I have to create those labels in that search form only and not rather ask the admin to fill them instead so that the admin is able to search them faster and smoothly?

**Comment by Harirai** [comment]
@kjain0073 Yes, change labels, like `First Name` to `First Name*`, labels are actually hardcoded so I think you'll have to change the template. I hope this is correct, but It would be better if you ask Sir for the confirmation.

**Comment by kjain0073** [comment]
> @kjain0073 Yes, change labels, like `First Name` to `First Name*`, labels are actually hardcoded so I think you'll have to change the template. I hope this is correct, but It would be better if you ask Sir for the confirmation.

@Monal5031 is this ok?

**Comment by Harirai** [comment]
@kjain0073 Are you working on this?

**Comment by abha224** [comment]
@kjain0073 Pls give us an update about the PR. Let us know if you are facing any problems while working on it.

**Comment by kjain0073** [comment]
@abha224  @Harirai  sincere apologies for delay in response. Actually i kinda ran into some errors with my setup and had to stop working on the system for a while. So i couldn't make any progress afterwards. I might not be able to work upon this issue as of now. Inconveniences caused are deeply regretted .

**Comment by yashshah2820** [comment]
@kjain0073 please don't create PR from develop branch

**Comment by Harirai** [comment]
SInce @kjain0073 is not able to work on this issue, closing the PR for now.

**Pull request closed without merging**
