### PR TITLE
Added Button in UI to link Zulip 

### LINKED ISSUE #1038: Add button in UI to link Zulip
## Description
As a user, I need to add a button to link our Zulip communication platform, so that I can have smooth communication through project.

### Update [Required]
- [ ] Screen shot in PR to show Button added
- [ ] Link to organisation group, Zulip

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

### PR DESCRIPTION
**Pull request by yash2189**
# Description
To add button in UI to link Zulip

Fixes #1038 

# Type of Change:

- User Interface

# How Has This Been Tested?
Successfully added button in UI to link Zulip. When a registered user is logged in the button is shown on the home page.

Button_ZULIP

# Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

### CODE REVIEW

**Comment by keshakaneria** [comment]
Did you do this locally? I am seeing 15 files are changed. You should edit the files locally and then push it into your forked repo in another branch and then send a PR in 1 commit and required files changed.

**Comment by yash2189** [comment]
apologies @keshakaneria this was my mistake I will do the required changes again.

**Comment by yash2189** [comment]
@keshakaneria I was setting up the project so I had done the migrations that was just for testing.

**Comment by keshakaneria** [comment]
Next time take care to have a look to list of files changed from the git bash before pushing it, so you only push the necessary edited files and nothing unnecessary.

**Pull request closed without merging**
