### PR TITLE
Pdf validation

### LINKED ISSUE #745: Additional checks should be included in volunteer/validation.py
## Description
As a developer/tested,
I need to be 101% sure that validations are checking all the cases,
so that users don't face issues at later stage while using the project.
Additional checks for resume PDF files can be added using `PyPDF2.PdfFileReader`
## Mocks
N/A

### Update [Required]
- [ ] Add extra checks pdf files
- [ ] Update tests accordingly.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
30 mins

### PR DESCRIPTION
**Pull request by AnweshaSen**
# Description
Added method to check the validity of uploaded resume pdf. Handles corrupted pdf upload.
Added test for corrupted pdf resume upload.

Fixes #745 

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
I have also written a test for the same. Then ran the test and made sure every tests pass.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yashshah2820** [comment]
@AnweshaSen can you upload a GIF of the work

**Comment by yashshah2820** [comment]
@AnweshaSen can you upload an image or a GIF showcasing the work done

**Comment by yashshah2820** [comment]
@AnweshaSen can you change the PR title according to the [PR guidelines](https://github.com/anitab-org/vms/wiki/Commit-Message-Style-Guide)

**Comment by mayburgos** [comment]
@AnweshaSen It's been a few months now. We're going to close this PR. If you come back, please ping us to re-open this PR. Thank you for this work!

**Pull request closed without merging**
