### PR TITLE
Add the newcomers link

### LINKED ISSUE #1039: Add the newcomers link of zulip chat for beginners
## Description
For a beginner, along with the channel of #vms we should also add the channel link of #newcomers in README.md, this would make the process a little fast forward for the beginners to communicate with community members and solve their beginner-specific issues.

### Update [Required]
- [ ] [Add the link of #newcomers from anitab-org.zulipchat.com]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by vaibhavarora102**
# Description
Added newcomers zulip link in the ReadMe.

Fixes #1039 

# Type of Change:
**Delete irrelevant options.**

- Documentation

# How Has This Been Tested?
git
Just changed readme

# Checklist:
**Delete irrelevant options.**

- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by satya7289** [comment]
@vaibhavarora102 please follow the commits message guildlines, also add how you tested by adding screenshots.

**Comment by vaibhavarora102** [comment]
git


kindly check screen shot and can you pls tell what guidelines you are talking of
thanks @satya7289

**Comment by satya7289** [comment]
> git
> 
> kindly check screen shot and can you pls tell what guidelines you are talking of
> thanks @satya7289

Add the screenshot to the description of the PR. Here is the guildlines https://github.com/anitab-org/vms/wiki/Commit-Message-Style-Guide

**Comment by vaibhavarora102** [comment]
@satya7289  is it okay now

**Comment by satya7289** [comment]
> @satya7289 is it okay now

Please add the screenshot to the `How has this tested section`.also squash the commits to 1 commit and follow commits message guildlines.

**Comment by vaibhavarora102** [comment]
@satya7289  I had made respective changes in the PR,
being new to open source I don't know the way to squash all the commits as they are already pushed. and had pushed two or from the same branch so, if I try to do change both will change kindly help.

**Comment by satya7289** [comment]
> @satya7289 I had made respective changes in the PR,
> being new to open source I don't know the way to squash all the commits as they are already pushed. and had pushed two or from the same branch so, if I try to do change both will change kindly help.

If you do some Google you will come to know how to do it.
This might help,
https://www.internalpointers.com/post/squash-commits-into-one-git
https://github.com/satya7289/Compter-Science-Stuffs/tree/master/git

**Pull request closed without merging**
