### PR TITLE
docs: added Python version Badge

### LINKED ISSUE #1052: Add a badge for Python version in README.md
## Description
README.md should have a badge for denoting the version of python needed.

## Mocks
README of [mentorship-backend](https://github.com/anitab-org/mentorship-backend/blob/develop/README.md).

Screenshot from 2020-08-29 20-56-52

## Definition of Done
- [ ] Badge should be added with appropriate version.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by atharwa-24**
# Description

Added Python Version Badge to README file,
logos to the Existing Badges in the README file
Removed extra blanc line

Fixes #1052 

# Type of Change:

- Documentation

# How Has This Been Tested?
Capture

# Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Great work @atharwa-24 🎉 
Thank you for your contribution!

**Review by gaurivn — APPROVED** [review]
pythonbadgevms
Thank you :clap:

**Comment by gaurivn** [comment]
@atharwa-24, in future for sending PRs please send from a new branch other than develop - it is most preferred.

**Comment by atharwa-24** [comment]
> Great work @atharwa-24 🎉 
> Thank you for your contribution!

Thank you

**Comment by atharwa-24** [comment]
> @atharwa-24, in future for sending PRs please send from a new branch other than develop - it is most preferred. 

Ok I will do that:)

**Review by SanketDG — APPROVED** [review]
LGTM :tada:

**Comment by isabelcosta** [comment]
@atharwa-24 can you please fix the merge conflicts? Then we can merge this :)

**Comment by atharwa-24** [comment]
> 
> 
> @atharwa-24 can you please fix the merge conflicts? Then we can merge this :)

fixed it!!

**Comment by atharwa-24** [comment]
@isabelcosta Fixed the merge conflict!! :)

**Pull request merged**
