### PR TITLE
Fix: Fixed links in Installation Guide

### PR DESCRIPTION
**Pull request by devkapilbansal**
# Description
When setting up locally, I realised that some links in Installation Guide are broken may be due to file name change. Therefore, I fix those minor errors.

# Type of Change:
**Delete irrelevant options.**

- Documentation

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by SanketDG — APPROVED** [review]
LGTM!

**Comment by SanketDG** [comment]
Did you fix any issue here?

**Comment by KapilBansal320** [comment]
@SanketDG No, I just correct the documentation. Should I open a issue first?

**Comment by SanketDG** [comment]
I do not know, it's up to the maintainers of the project.

**Comment by KapilBansal320** [comment]
@Kajol-Kumari @atharwa-24 please review it

**Comment by devkapilbansal** [comment]
@vj-codes @isabelcosta review this too

**Review by atharwa-24 — APPROVED** [review]
LGTM!

**Review by isabelcosta — APPROVED** [review]
Great work @devkapilbansal 👏 🎉 
Thank you for your contribution!

**Pull request merged**
